### ISSUE TITLE
Missing angularjs-slider module causes blank screen 

### ISSUE THREAD

**Issue by tzachari** [covid19database/phone-app-no-fork#7]
From our discussion earlier:

When building and installing from repo, the app opens as a blank screen.

Based on inspection, source of the problem looks to be a missing `angularjs-slider` module and failed instantiation of `rzModule`.

<img width="1570" alt="angularjs-slider-error" src="https://user-images.githubusercontent.com/2251502/78174288-0387cf00-7427-11ea-8135-d75e41645bed.png">

Removing reference to `rzModule` in diary's [current.js](https://github.com/covid19database/phone-app/blob/f8db039d97f3d403f7a1dbd16174c5f0c4423fee/www/js/diary/current.js#L6) seems to fix the issue.

**Comment by shankari** [comment]
I removed that module in 891a295ff28837e6ef0fc762f733634de19f68ea.
Not sure why it is not failing for me...

**Comment by shankari** [comment]
This is very weird. I cannot reproduce this. I have tried emulating it from the cordova command line; I have tried running it from android studio. I don't get the error. But it is in the index.html and it should generate the error.

I looked at the console logs, and I don't see a FileNotFound for the rzsider.min.js

**Comment by shankari** [comment]
aha! I looked at the network tab and this is apparently in my build?

```
Request URL:file:///android_asset/www/lib/angularjs-slider/dist/rzslider.min.js
Request Method:GET
Status Code:200 OK (from cache)
```

**Comment by shankari** [comment]
And I do in fact have it in my lib folder as well.

```
$ find www/ -name \*rzslider\*
www//lib/angularjs-slider/dist/rzslider.css
www//lib/angularjs-slider/dist/rzslider.js
www//lib/angularjs-slider/dist/rzslider.d.ts
www//lib/angularjs-slider/dist/rzslider.scss
www//lib/angularjs-slider/dist/rzslider.min.js
www//lib/angularjs-slider/dist/rzslider.min.css
www//lib/angularjs-slider/rzslider.d.ts
www//lib/angularjs-slider/src/rzslider.js
www//lib/angularjs-slider/src/rzslider.less
```

I think that the problem is that I ran `bower update` first, when the `rzslider` was in `bower.json`. Then I removed it from `bower.json`. Since it was removed from `bower.json`, bower didn't know about it any more and didn't remove it.

I'm just going to add the dependency back for now. Should think about how to add basic WSOD CI for later but no time now.
